---
- name: Install NGINX
  apt:
    name: "{{ install_package }}"
    state: present
    update_cache: yes
  notify: restart "{{ install_package }}"

- name: Create website directory
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Deploy index.html to the website
  copy:
    src: files/index.html  # Path to your index.html
    dest: /var/www/html/index.html

- name: Deploy "{{ install_package }}" config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/{{ install_package }}/nginx.conf
  notify: restart "{{ install_package }}"

# - name: Ensure NGINX is running
#   service:
#     name: nginx
#     state: started
#     enabled: true


  