---
- name: Update system packages
  apt:
    name: '*'
    state: latest

- name: Install dependencies
  apt:
    name:
      - python3
      - python3-pip      
      - python3-venv
    state: present
    update_cache: yes

- name: Create and Activate Virtual Environment
  command: "{{ item }}"
  with_items:
    - python3 -m venv myenv
    - source myenv/bin/activate

- name: Install Gunicorn if not already installed
  pip:
    name: gunicorn
    executable: pip3


- name: Install Flask using pip3
  pip:
    name: Flask
    state: present
    executable: pip3

- name: Copy Flask app to the target machine
  copy:
    src: templates/flask_app.j2
    dest: /home/ubuntu/myflaskapp/
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Create a systemd service unit file for Flask app
  template:
    src: flask_app.j2
    dest: /etc/systemd/system/flask_app.service
    mode: '0644'

- name: Reload systemd to pick up the new service
  systemd:
    daemon_reload: yes

- name: Enable the Flask app service
  systemd:
    name: flask_app.service
    enabled: yes

- name: Enable and start Flask app service
  systemd:
    name: flask_app.service
    enabled: yes
    state: started