---

- name: Update APT
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - nginx
    state: present

- name: Create project directory
  file:
    path: /opt/flask_app
    state: directory
    mode: '0755'

- name: Set up virtualenv
  command: python3 -m venv /opt/flask_app/mvenv
  args:
    creates: /opt/flask_app/mvenv

- name: Install Flask and Gunicorn in mvenv
  pip:
    virtualenv: /opt/flask_app/mvenv
    name:
      - flask
      - gunicorn

- name: Upload app.py
  copy:
    src: files/app.py
    dest: /opt/flask_app/app.py
    mode: '0644'

- name: Upload Gunicorn systemd service
  copy:
    src: files/flask.service
    dest: /etc/systemd/system/flask.service
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Flask service
  systemd:
    name: flask
    enabled: yes
    state: restarted

- name: Upload Nginx config
  copy:
    src: files/flask_nginx.conf
    dest: /etc/nginx/sites-available/flask
    mode: '0644'

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/flask
    dest: /etc/nginx/sites-enabled/flask
    state: link
    force: yes

- name: Disable default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
