---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify: restart nginx

- name: Create website directory
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Deploy index.html to the website
  copy:
    src: files/index.html  # Path to your index.html
    dest: /var/www/html/index.html

- name: Deploy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Ensure NGINX is running
  service:
    name: nginx
    state: started
    enabled: true

handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted

  